apiVersion: v1
kind: Pod
metadata:
  name: meghdo-agent
  namespace: jenkins
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  serviceAccountName: jenkins
  securityContext:
    runAsGroup: 1000
    runAsUser: 1000
  volumes:
    - name: docker-sock
      persistentVolumeClaim:
        claimName: "jenkins-agents"
    - name: workspace-volume
      emptyDir: {}
  containers:
    - name: jnlp
      image: jenkins/inbound-agent:latest
      imagePullPolicy: Always
      args: ["-url", "http://jenkins.jenkins.svc.cluster.local:8080", "-workDir", "/home/jenkins/agent"]
      volumeMounts:
        - name: workspace-volume
          mountPath: /home/jenkins/agent
        - name: docker-sock
          mountPath: "/var/run/docker.sock"
      env:
        - name: JENKINS_URL
          value: "http://jenkins.jenkins.svc.cluster.local:8080"
        - name: JENKINS_TUNNEL
          value: "jenkins-agent.jenkins:50000"
      resources:
        requests:
          memory: "128Mi"
          cpu: "128m"
        limits:
          memory: "512Mi"
          cpu: "512m"
    - name: infra-tools
      image: alpine/helm:3.11.1
      command: ["sleep"]
      args: ["9999999"]
      volumeMounts:
        - name: workspace-volume
          mountPath: /home/jenkins/agent
      resources:
        requests:
          memory: "128Mi"
          cpu: "128m"
        limits:
          memory: "512Mi"
          cpu: "512m"
    - name: aws
      image: amazon/aws-cli
      imagePullPolicy: Always
      command: [ "sleep" ]
      args: [ "9999999" ]
      securityContext:
        runAsUser: 0
        runAsGroup: 0